name: Backend - Golang Continous Integration
on:
  pull_request:
    paths:
      - "api/**"
      - ".github/workflows/be-ci.yaml"

jobs:
  testing:
    name: Go Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.16']
    defaults:
      run:
        shell: bash
        working-directory: api
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
      - name: Go '1.16'
        uses: actions/setup-go@v1
        with:
            go-version: ${{ matrix.go }}
      - name: Run test
        run: go test -test.v -test.coverprofile=coverage.out -test.covermode=count ./...
        
  lint:
    name: Golang-CI Lint
    runs-on: ubuntu-latest
    env:
      GO111MODULES: off
    strategy:
      matrix:
        go: ['1.16']
    defaults:
      run:
        shell: bash
        working-directory: api
    steps:
      - uses: actions/checkout@v2
      - name: Go '1.16'
        uses: actions/setup-go@v1
        with:
            go-version: ${{ matrix.go }}
      - name: Run go mod tidy
        run: go mod tidy
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.29