name: Mobile Apps - Flutter Continous Integration
on:
  pull_request:
    paths:
      - "apps/**"
      - ".github/workflows/flutter-ci.yaml"

jobs:
  testing:
    name: Flutter testing and build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apps
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Java 12.x
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Use flutter action
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Run get
        run: flutter pub get
      - name: Run test
        run: flutter test
      - name: Run build
        run: flutter build apk